config/routes.rb
Rails.application.routes.draw do

resources :articles
resources :users
resources :sessions, only: [:new, :create, :destroy]

match '/mission',     to: 'static_pages#mission',    via: 'get'
match '/stories',     to: 'static_pages#stories',    via: 'get'
match '/contact',     to: 'static_pages#contact',    via: 'get'
match '/about',       to: 'static_pages#about',      via: 'get'
match '/admin',       to: 'static_pages#admin',      via: 'get'

match '/signup',      to: 'users#new',               via: 'get'

match '/signup',      to: 'users#new',               via: 'get'
match '/signin',      to: 'sessions#new',            via: 'get'
match '/signout',     to: 'sessions#destroy',        via: 'delete'

root 'static_pages#stories'

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :originallink, presence: true
  validates :region, presence: true
  validates :country, presence: true

has_attached_file :image, 
    :path => ":rails_root/public/system/:class/:attachement/:id/:basename_:style.:extension",
    :url => "/system/:class/:attachement/:id/:basename_:style.:extension",
    :removable => true,
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :medium   => ['160x160#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :medium   => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }


  validates_attachment :image,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }



end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

		validates 	:name,  presence: true, length: { maximum: 50 }
		VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
		validates 	:email, presence: true, 
					format: { with: VALID_EMAIL_REGEX }, 
					uniqueness: { case_sensitive: false }
		has_secure_password
		validates :password, presence: true

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :signed_in_user, only: [:edit, :update, :destroy]

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			flash.now[:notice] = 'Please fill out all the fields.'
			render 'new'
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	def index
		@articles = Article.all.paginate(page: params[:page], per_page: 6)
	end

	def show
		@article = Article.find(params[:id])
	end



private

	def article_params
		params.require(:article).permit(:title, :region, :text, :image, :originallink, :country)
	end

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to admin_url, notice: "Please sign in." unless signed_in?
			end
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		render 'new'
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or root_url
		else
			flash.now[:error] = 'Invalid signin. Please try again.'
			render 'new'

		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end

  def mission
  end

  def stories
	# @articles = Article.order("created_at desc").limit(6)
	@articles = Article.order("created_at desc").limit(16)
  end

  def admin
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	http_basic_authenticate_with name: "pascal", password: "krummenacher", 
	only: [:create]

before_action :signed_in_user, only: [:edit, :update, :show, :destroy]


	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new(params[:id])
		if @user.save

		else
			render 'new'
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "User updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
	    User.find(params[:id]).destroy
	    flash[:success] = "User deleted."
	    redirect_to users_url
  	end


	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to signin_url, notice: "Please sign in." unless signed_in?
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
  	!current_user.nil?
  end

  def current_user=(user)
  	@current_user = user
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
	<%= form_for(@article, :html => { :multipart => true, :class => 'pure-form pure-form-stacked form' } ) do |f| %>

		<div class="pure-g">

			<%= f.text_field :title, :placeholder => "Title...", :class => "pure-input-1 field", :required => "true" %>

		    <%= f.text_field :region, :placeholder => "Region...", :class => "pure-input-1 field", :required => "true" %>


			<%= f.text_field :country, :placeholder => "Country...", :class => "pure-input-1 field", :required => "true" %>

		    <%= f.text_area :text, :placeholder => "Text...", :class => "pure-input-1", :required => "true" %>

		    <%= f.text_field :originallink, :placeholder => "Original Article URL...", :class => "pure-input-1 field", :required => "true" %>

			<div style="clear:right">		  	

			  	<% if @article.image.present? %>
					<%= image_tag @article.image.url(:thumb) %><br>
				<% end %>

				<%= f.file_field :image %>
				
				<br>

			</div>

			<div class="pure-u-1", id="button_area" >
				<%= link_to 'Back', :back, :class => "pure-button" %>
			    <%= f.submit 'Save Article', :class => 'pure-button pure-button-primary' %>
				<% if local_assigns.has_key? :edit %>
					<%= link_to 'Delete', article_path(@article),
				          method: :delete, data: { confirm: 'Are you sure?'}, :class => "pure-button button-cta" %>
				<% end %>
			</div>

		</div>

	<% end %>

</div>

app/views/articles/edit.html.erb
<div class="content-wrapper">
<%= render 'form', { edit: '' } %>
</div>

app/views/articles/index.html.erb
<% if @articles.present? %>

      <div class="content-wrapper">

        <table class="table">
          <thead>
            <tr>
              <th>Created</th>
              <th>Title</th>
              <th>Article Preview</th>
              <th>Article Image</th>
              <th>Options</th>
            </tr>
          </thead>

          <% @articles.each do |article| %>
            <tr>
            <td><%= article.created_at.to_formatted_s(:short) %></td>
            <td><%= article.title %></td>
            <td><%= truncate(article.text, :length => 50, :separator => ' ') %><br><br></td>
            <td><%= image_tag article.image.url(:thumb) %></td>
            <td><%= link_to 'Show', article_path(article) %>
                <%= link_to 'Edit', edit_article_path(article) %>
                <%= link_to 'Delete', article_path(article),
                          method: :delete, data: { confirm: 'Are you sure?'}
                          %></td>
            </tr>
            <% end %>

        </table>

      <%= will_paginate @articles %>

      </div>

<% else %>
      <div class="content-wrapper">
        <p class="center"> No articles! </p>
          <br>
        <div class="pure-u-1 center" >
          <%= link_to 'Back', :back, :class => "pure-button" %>
        </div>
      </div>

<% end %>

app/views/articles/new.html.erb
<div class="content-wrapper">

<%= render 'form' %>

</div>

app/views/articles/show.html.erb
<div class="content-wrapper">



	<p style="text-align: left">
	  <strong>
	  <%= @article.title %>
	  </strong>
	</p>
	 
	<p>
		<%= @article.region + ', ' %><i><%= (@article.country).to_s %> </i>
	</p>

	<p style="text-align: justify; text-justify:inter-word;">
		<%= simple_format(@article.text, :class => 'articlebody') %>
	</p>

	<br>

	<%= link_to 'Back', :back, :class => "pure-button" %>

	<%= link_to 'Original Article', @article.originallink, :class => "pure-button",:target => "_blank" %>
	
	<% if signed_in? %>

	<%= link_to 'Edit', edit_article_path(@article), :class => "pure-button" %>

	<%= link_to 'Delete', article_path(@article),
	                  method: :delete, data: { confirm: 'Are you sure?'}, :class => "pure-button", :style => "display: none" %>

	<% end %>

</div>

app/views/layouts/_admin.html.erb
<div class="">

<% if signed_in? %>
	<%= link_to "Users", '#' %>
	<%= link_to "Profile", current_user %>
	<%= link_to "Settings", '#' %>
	<%= link_to "Sign out", signout_path, method: "delete" %>

<% else %>
	<%= link_to "Sign in" %>

<% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
	  <title>News in Brief</title>

	  	<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:400">

		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

		<link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>

	  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>

	</head>

<div class="content", style="margin-bottom:10%; padding-bottom:10%">

		<body>
		<%= render "static_pages/header" %>

		<%= yield %>

		</body>

	
</div>

<!-- <div id="footer">
		<div id="text">
			<%= link_to "http://www.facebook.com/" do%>
			<%= image_tag "icons/facebookw.png", :size => '32x32', :class => 'icon' %>
			<% end %>
			<%= mail_to "contactbrieftoday@gmail.com" do%>
			<%= image_tag "icons/mailw.png", :size => '32x32', :class => 'icon' %>
			<% end %><br>


		</div>
</div> -->

</html>

app/views/static_pages/_header.html.erb
<div class="center header">

	<%= link_to stories_path do%>
	<%= image_tag "logo.png" %>
	<% end %>

		<div class="pure-menu pure-menu-open pure-menu-horizontal sansserif", style="margin-top: .5em">
		    <ul>

		        <li><%= link_to "STORIES", stories_path %></li>
		        <li><%= link_to "MISSION", mission_path %></li>
		        <li><%= link_to "ABOUT", about_path %></li>
		        <li><%= link_to "CONTACT", contact_path %></li>
		        <% if signed_in? %>
		        <li><%= link_to "ADMIN", :controller => "static_pages", :action => "admin" %></li>
		        <% end %>
		    </ul>
		</div>



</div>

app/views/static_pages/about.html.erb
<div class="content-wrapper">
<p>

<strong>Brief.</strong> was started at Queen Mary University of London as a reaction to what we thought was informative, yet too intricate news that we were seeing from major news agencies.
<br />
<br />
At Brief. we take what we think are important articles from trusted news outlets like CNN, The Times, The Guardian or Al Jazeera and shrink them into articles no longer than 150 words every Monday, Wednesday and Friday. 
<br />
<br />
Currently we are briefing about 6 articles a day with hopes to increase this number to 8 shortly. As it is not in Brief.’s philosophy to drown readers in current events this number is unlikely to move up far beyond 16. We are always looking for suggestions and we are always looking for new people; so please do get in touch with us at our ‘Contact’ page if you would like to join the team. 

</div>

app/views/static_pages/admin.html.erb
<div class="content-wrapper center">

<% if signed_in? %>
<p>Administrative Privileges. Use wisely.</p>
		
	<%= link_to 'New Article', new_article_path, :class => "pure-button pure-button-primary" %>
	<%= link_to "All Articles", articles_path, :class => "pure-button" %>	
	<%= link_to "All Users", users_path, :class => "pure-button" %>	
	<%= link_to "Sign out", signout_path, method: "delete", :style => "background: rgb(202,60,60); color: white;" ,:class => "pure-button" %>

<% else %>

	<%= link_to "Sign in", signin_path, method: "get", :class => "pure-button" %>

<% end %>

</div>

app/views/static_pages/contact.html.erb
<div class="content-wrapper">

<p>

<b>Email</b>
<br />
contactbrieftoday@gmail.com
<br /><br />

<b>Phone</b>
<br />
12345678

<br /><br />
<b>Social media</b>
<br /><br />
</p>

</div>

app/views/static_pages/mission.html.erb
<div class="content-wrapper">

<p>
<strong>In today's</strong> increasingly fast-paced society, people need to be efficient in getting through their pre-existing obligations, yet also simultaneously be informed of current events. 
<br />
<br />
Conventional news-media outlets provide the necessary information, but in a way that requires already limited time and energy. A possible solution to this 21st-dilemma would be an online source of the day's most integral and vital happenings, summarized in a way that highlights the essentials. 
<br />
<br />
It is because of this reason we have created Brief.- a resource containing straightforward descriptions of international events with widespread repercussions.
<br />
<br />
Our purpose with this site is therefore to provide news in a format that is compatible to our fast-paced life, but also hopefully spread awareness of global affairs.

</p>

</div>

app/views/static_pages/stories.html.erb
<ul class="grid cs-style-3">
	<% @articles.each do |article| %>
		<li>
	        <figure>
	        	<% if article.image.blank? %>
	        	<%= link_to image_tag(("missing.png"), :class => "img"), article_path(article) %>
				<% else %>
	            <%= link_to image_tag(article.image(:medium), :class => "img"), article_path(article) %>
	            <% end %>

	            <%= link_to(article_path(article)) do %>
	            <figcaption>
	                <h3><%= article.title%></h3>
	                <p class="center"><%= article.region.upcase %></p>
	            </figcaption>
	            <% end %>
	        </figure>
    	</li>

    	<% end %>

</ul>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="pure-form">
  <div class="pure-g">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "pure-button pure-button-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper">

<ul class="users", style="text-align: center">
  <% @users.each do |user| %>

      <%= link_to user.name, user %>
  <% end %>
</ul>

</div>

app/views/users/new.html.erb
<div class="content-wrapper">

<div class="pure-form">
  <div class="pure-g">
    
    <%= form_for(@user) do |f| %>

        <%= f.text_field :name, :placeholder => "Name...", :class => "pure-input-1 field", :required => "true"  %>

        <%= f.text_field :email, :placeholder => "Email...", :class => "pure-input-1 field", :required => "true"  %>

        <%= f.password_field :password, :placeholder => "Password...", :class => "pure-input-1 field", :required => "true"  %>

        <%= f.password_field :password_confirmation, :placeholder => "Re-Type Password...", :class => "pure-input-1 field", :required => "true"  %>

        <%= f.submit "Create my account", :class => "pure-button pure-button-primary" %>

    <% end %>

  </div>
</div>

</div>

app/views/users/show.html.erb
<div class="container-wrapper">

<p class="center">
<%= @user.name %>, 
<%= @user.email %>

<% if signed_in? %>
    | <%= link_to "delete", @user, method: :delete,
                                  data: { confirm: "You sure?" } %>
<% end %>
</p>
</div>